$("#one").css("background","#bbffaa");
$(".mini").css("background","#AFEBFF");
$("div").css("background","#FFF7BD");
$("*").css("background","#bbffaa");
$("span , #two").css("background","#AFEBFF");
$("body div").css("background","#FFF7BD");
$("body > div").css("background","#bbffaa");
$(".one + div").css("background","#ffffff");
$("#two ~ div").css("background","#FFF7BD");
$("div:first").css("background","#ffffff");
$("div:last").css("background","#FF7D99");
$("div:not(.one)").css("background","#FF7D99");
$("div:even").css("background","#EE95FF");
$("div:odd").css("background","#FFF7BD");
$("div:eq(3)").css("background","#FF7D99");
$("div:gt(4)").css("background","#FF186F");
$("div:lt(2)").css("background","#FF186F");
$(":header").css("background","#bbffaa");
$(":animated").css("background","#bbffaa");
$(":focus").css("background","#bbffaa");
$("div:contains(di)").css("background","#FF7D99");
$("div:empty").css("background","#ffffff");
$("div:has(.mini)").css("background","red");
$("div:parent").css("background","green");
$("div:visible").css("background","#ff6500");
$("div:hidden").show(3000);